### ISSUE TITLE
[FEATURE] Add external url override for Foundry join link

### ISSUE THREAD

**Issue by cswendrowski** [cswendrowski/FoundryVTT-Discord-Rich-Presence#11]
Foundry only knows its own IP, such as `http://204.48.23.51:80`.
Users with vanity links would like to configure the Join to use `https://foundry.myinstance.com`

**Comment by Azzurite** [comment]
I noticed this as well, only shows disabled "join" button for me when I try to invite someone

**Comment by sPOiDar** [comment]
Is this resolved by setting the `hostname`/`routePrefix` parameters on your Foundry instance?

**Comment by cswendrowski** [comment]
@sPOiDar that appears to be the case. Thanks for bringing this to my attention!
