### ISSUE TITLE
Hide console window

### ISSUE THREAD

**Issue by NutritiousCookie** [cswendrowski/FoundryVTT-Discord-Rich-Presence#17]
The RichPresenceApi.exe console pops up every time I launch the game. Please hide it.

**Comment by cswendrowski** [comment]
@NutritiousCookie that is the native behavior of launching a console app via the commandline (which is the only option this module has of automatically launching it).

To avoid this behavior, register the Companion App as a background Service and uncheck this setting:
![image](https://user-images.githubusercontent.com/15639841/87468521-6a4c8500-c5df-11ea-96fd-f10d955fa0d8.png)
