### ISSUE TITLE
Disable voice?

### ISSUE THREAD

**Issue by nearlyNonexistent** [cswendrowski/FoundryVTT-Discord-Rich-Presence#18]
Might be good idea to have an option to disable the voice mode completely.

**Comment by cswendrowski** [comment]
Does the "Auto Join Voice" option not cover what you're looking for?

**Comment by nearlyNonexistent** [comment]
I would like to remove the button that says "join voice" in the player list.

**Comment by cswendrowski** [comment]
@nearlyNonexistent this feature is available as of Module version 2.2.0
