### ISSUE TITLE
Anyway to get Discord Channel text chat to show up in Foundry VTT?

### ISSUE THREAD

**Issue by Sonny-Crockett** [cswendrowski/FoundryVTT-Discord-Rich-Presence#19]

**Comment by cswendrowski** [comment]
Hey there @Sonny-Crockett! Discord and Foundry both have extensive API's, so such a connection is possible. This module focuses only on the Discord GameSDK API such as Rich Presence, and I have no plans to expand outside of that forte. This project is promising but is going the wrong direction: https://github.com/nearlyNonexistent/foundry-discordbridge

I hope someone makes what you're looking for, it sounds interesting!

**Comment by Sonny-Crockett** [comment]
Thank you!
