### ISSUE TITLE
API option to run in background

### ISSUE THREAD

**Issue by BadgerKing7** [cswendrowski/FoundryVTT-Discord-Rich-Presence#20]
Currently, as far as I can tell, there is no method through which the local API can be made to run in the background, without opening a CMD window. This still happens even when I try to explicitly run it without a window via batch file or Visual Basic script.

Adding the option to run the local API in the background, without a window, would make it less intrusive and it would make users like me feel better about using it.

Going one step further, in my opinion, the local API should by default run without a window. Outputting to a command window should be only a debug/troubleshooting feature.

**Comment by cswendrowski** [comment]
Hey there @BadgerKing7! Your instructions will depend on what OS you're using, but on Windows you can run the .exe as a background service: https://www.howtogeek.com/50786/using-srvstart-to-run-any-application-as-a-windows-service/
