### ISSUE TITLE
MAC Security Issue

### ISSUE THREAD

**Issue by justinthejaguar** [cswendrowski/FoundryVTT-Discord-Rich-Presence#21]
I am able to bypass the first security block, but it seems that the second is due to another library that it calls for.

<img width="415" alt="image" src="https://user-images.githubusercontent.com/38022481/96798832-b756a900-13cf-11eb-9a73-566436a07c03.png">
 
Catalina makes life difficult. Since it calls the security issue every time, when I allow it, it has already cancelled the process.

**Comment by cswendrowski** [comment]
Hey there @justinthejaguar! Can you run chmod 777 against the entire folder and let me know if that resolves it? Thanks!

**Comment by Spectre-63** [comment]
it's not a matter of making the files executable, but that the later MacOS versions flag "unsigned" apps (for clarification, it has to be signed using an Apple certificate) as potentially unsafe and preventing the user from running them.  The only way I was able to bypass this was using the instructions here:
https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave

**Comment by cswendrowski** [comment]
Thanks for the instructions @Spectre-63 - I'll add those to the Readme
