### ISSUE TITLE
MacOS does not auto-launch the RichPresenceAPI, even after successfully launching once

### ISSUE THREAD

**Issue by Spectre-63** [cswendrowski/FoundryVTT-Discord-Rich-Presence#22]
First - thanks for producing this module. :)

Second - instructions are a little thin, but I managed to work around the Catalina app signing issue by using the instructions here https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave 

Unfortunately the API still does not automatically launch when entering Foundry - I was able to work around this by having the API run at user login and NOT auto-close when leaving Foundry.  Just hoping to find a cleaner way to set this up.

**Comment by cswendrowski** [comment]
Thanks for the info @Spectre-63 - I'm sorry to hear that the lack of app-signing prevents auto-launch, but at the least running it at user login works. If you have thoughts on how to make this easier, I'm all ears, but this is likely the only option we have available to us

**Comment by Spectre-63** [comment]
I'm not certain that it's a case that the app-signing is _preventing_ auto-launch as the app is now in a state that is "trusted" but still will not launch.  You may be right, however....I'm not sure how fully MacOS supports .NET
