### ISSUE TITLE
Suggestion: Deeper Discord integration

### ISSUE THREAD

**Issue by HisWatchIsEnded** [cswendrowski/FoundryVTT-Discord-Rich-Presence#24]
This is a great FVVT module.

Suggest perhaps creating the Companion API as an app installable from within discord as opposed to a standalone executable.
Would really love to see the above and:

1. Ability to configure a specific discord server (my own).
2. Ability to configure a specific text and voice channel to use (all my game use private discord channels).
3. Make presence messages available for macro usage so that it can be changed by me directly from the FVVT UI.

**Comment by cswendrowski** [comment]
To the best of my knowledge you can't install 3rd party apps into Discord

1 & 2) The Discord GameSDK has a hard limitation that it doesn't interact with channels and servers in the Discord client. Check out the full details in the writeup here: https://github.com/cswendrowski/FoundryVTT-Discord-Rich-Presence/wiki/How-does-this-work%3F

3) The module has an API you are free to hit inside of Foundry with a macro. You can access it at `window.DiscordRichPresence` - take a look at how status updates are sent here https://github.com/cswendrowski/FoundryVTT-Discord-Rich-Presence/blob/master/richpresence.js#L105

**Comment by HisWatchIsEnded** [comment]
https://discord.com/developers/applications

Nightbot, StreamDeck, DnD Beyond, Avrae - all examples of Discord API apps that can be installed within Discord.

**Comment by cswendrowski** [comment]
> 
> 
> [discord.com/developers/applications](https://discord.com/developers/applications)
> 
> Nightbot, StreamDeck, DnD Beyond, Avrae - all examples of Discord API apps that can be installed within Discord.

These are Bots that use the Discord API. Discord Rich Presence uses the Discord Game SDK, a completely separate bundle of features that Discord provides. You cannot set the Rich Status from the API, and you cannot install as a Bot from the SDK.

Unfortunately these are the limits imposed on me by what Discord offers. If you'd like to learn more, this resource is still a great one to learn about what the Discord Game SDK is and how this module uses it: https://github.com/cswendrowski/FoundryVTT-Discord-Rich-Presence/wiki/How-does-this-work%3F
